### ISSUE TITLE
Problems with Android 2.3.3

### ISSUE THREAD

**Issue by abdavid** [groovetrain/jQuery.mobile-Tabs#2]
There seems to be an issue with this plugin and  the Android 2.3.3 webbrowser.

From what we have learned during initial debugging, the problem seems to reside within the following code.  

<code>
currentTab: function() {
        var $tabs = this.element,
        $navbtns = $tabs.find("a");
        return this.element.find('.ui-btn-active').parent().prevAll().length;
},
</code>

and will fail here:

<code>
$content.children('#' + $navbtns.eq($this.currentTab()).attr('href')).addClass('ui-tabs-content-active');
</code>

**Comment by groovetrain** [comment]
Is this still an issue with the new version?

**Comment by abdavid** [comment]
Closing this old thing.
