### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by chillu** [groovetrain/jQuery.mobile-Tabs#3]
Hey there, awesome work, exactly what I was looking for :) Unfortunately I can't use the code as it doesn't spell out the license terms, which means its proprietary copyright by default. I'd recommend BSD (http://www.opensource.org/licenses/BSD-2-Clause)

Ingo

**Comment by groovetrain** [comment]
Ok, so could you please tell me how to add a license, or point me to somewhere that tells how?  I have never done so before, and if it'd help you out, that's all good.  Sorry it took so long to respond :)

**Comment by chillu** [comment]
Hey there, just copy the part under "Here is the license template:", replace the placeholders (owner, year), and add it to your README.md :)

**Comment by groovetrain** [comment]
welp, I finally did it.

**Comment by chillu** [comment]
Thanks man!
