### ISSUE TITLE
jQuery version

### ISSUE THREAD

**Issue by maxnis** [groovetrain/jQuery.mobile-Tabs#5]
Works well up to the version 1.7.2, 
when I tried to switch to the version 1.8.1 (jqm 1.2.0) - I get the error:
Uncaught Error: Syntax error, unrecognized expression: ##my_tab_id 
method _create, line 54:
removing the '#' symbol fixes the problem in  jq 1.8.1:
$content.children('#' + $navbtns.eq($this.currentTab()).attr('href')).addClass('ui-tabs-content-active');

**Comment by piranna** [comment]
I have this fixed on https://github.com/piranna/jQuery.mobile-Tabs
